version: '3.2'
services:
  influxdb:
    build: influxdb
    container_name: influxdb
    env_file: configuration.env
    ports:
      - 8086:8086
      - 8083:8083
      - 2003:2003
    volumes:
      - ../volumes/influxdb:/var/lib/influxdb
  telegraf:
    image: telegraf
    restart: always
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS: /rootfs/sys
      HOST_ETC: /rootfs/etc
    hostname: localhost
    volumes:
     - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /sys:/rootfs/sys:ro
     - /proc:/rootfs/proc:ro
     - /etc:/rootfs/etc:ro
  prometheus:
    build: prometheus
    container_name: prometheus
    ports:
      - 8091:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml   
    depends_on:
      - telegraf
networks:
  default:
    external:
      name: performance-test






     

