#!/bin/bash

### Imports
source sh/scripts/global-variables.sh

#
# Run Test
#
function executeTest(){
    sudo $JMETER_LOCATION -n -t $JMX_FILE -l $JTL_PATH \
    -JJMETER_TARGET_CONCURRENCY="$JMETER_TARGET_CONCURRENCY" \
    -JJMETER_RAMP_UP_TIME="$JMETER_RAMP_UP_TIME" \
    -JJMETER_RAMP_UP_STEPS_COUNT="$JMETER_RAMP_UP_STEPS_COUNT" \
    -JJMETER_HOLD_TARGET_RATE_TIME="$JMETER_HOLD_TARGET_RATE_TIME" \
    -JJMETER_MESSAGE_EVENT="$JMETER_MESSAGE_EVENT" \
    -JJMETER_MESSAGE_ORIGIN="$JMETER_MESSAGE_ORIGIN" \
    -JJMETER_SERVER_PATH="$JMETER_SERVER_PATH" \
    -JJMETER_SERVER_HOST="$JMETER_SERVER_HOST"  \
    -JJMETER_SERVER_PROTOCOL="$JMETER_SERVER_PROTOCOL" \
    -JJMETER_SERVER_PORT="$JMETER_SERVER_PORT" \
    -JJMETER_INFLUXDB_URL="$JMETER_INFLUXDB_URL"  \
    -JJMETER_INFLUXDB_TEST_TITLE="$JMETER_INFLUXDB_TEST_TITLE" \
    -JJMETER_INFLUXDB_APP_NAME="$JMETER_INFLUXDB_APP_NAME" \
    -JJMETER_MESSAGE_TYPE="$JMETER_MESSAGE_TYPE" \
    -JJMETER_REQUEST="$JMETER_REQUEST"
}
