version: '3'
services:
  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis/data:/redis/data
      - ./volumes/redis/redis.conf:/usr/local/etc/redis/redis.conf
